INSERT INTO words (week, week_label, en, de) VALUES
(1, 'What can you see?', 'what', 'was'),
(1, 'What can you see?', 'can', 'können'),
(1, 'What can you see?', 'you', 'du, dich, dir, Sie, ihnen'),
(1, 'What can you see?', 'see', 'sehen'),
(1, 'What can you see?', 'I', 'ich'),
(1, 'What can you see?', 'I can see', 'Ich kann sehen'),
(1, 'What can you see?', 'a, an', 'ein, eine'),
(1, 'What can you see?', 'car', 'Auto'),
(1, 'What can you see?', 'hear', 'hören'),
(1, 'What can you see?', 'colour', 'Farbe'),
(1, 'What can you see?', 'is', 'ist'),
(1, 'What can you see?', 'your', 'dein(e), euer, eure, Ihr(e)'),
(1, 'What can you see?', 'favourite', 'lieblings'),
(2, 'Farben & Spiel', 'red', 'rot'),
(2, 'Farben & Spiel', 'orange', 'orange'),
(2, 'Farben & Spiel', 'yellow', 'gelb'),
(2, 'Farben & Spiel', 'green', 'grün'),
(2, 'Farben & Spiel', 'blue', 'blau'),
(2, 'Farben & Spiel', 'purple', 'lila'),
(2, 'Farben & Spiel', 'pink', 'rosa'),
(2, 'Farben & Spiel', 'brown', 'braun'),
(2, 'Farben & Spiel', 'white', 'weiß'),
(2, 'Farben & Spiel', 'grey', 'grau'),
(2, 'Farben & Spiel', 'black', 'schwarz'),
(2, 'Farben & Spiel', 'game', 'Spiel'),
(2, 'Farben & Spiel', 'I spy with my little eye', 'Ich sehe was, was du nicht siehst'),
(2, 'Farben & Spiel', 'something', 'etwas'),
(2, 'Farben & Spiel', 'the', 'der, die, das'),
(2, 'Farben & Spiel', 'dog', 'Hund'),
(2, 'Farben & Spiel', 'yes', 'ja'),
(3, 'Zahlen & Kennenlernen', 'kid', 'Kind'),
(3, 'Zahlen & Kennenlernen', 'my name is', 'Ich heiße, ich bin'),
(3, 'Zahlen & Kennenlernen', 'hi', 'hallo, hi'),
(3, 'Zahlen & Kennenlernen', 'hello', 'hallo, hi'),
(3, 'Zahlen & Kennenlernen', 'we', 'wir'),
(3, 'Zahlen & Kennenlernen', 'we''re, we are', 'wir sind'),
(3, 'Zahlen & Kennenlernen', 'from', 'von, aus'),
(3, 'Zahlen & Kennenlernen', 'in', 'in'),
(3, 'Zahlen & Kennenlernen', 'too', 'auch'),
(3, 'Zahlen & Kennenlernen', 'but', 'aber'),
(3, 'Zahlen & Kennenlernen', 'live', 'leben, wohnen'),
(3, 'Zahlen & Kennenlernen', 'now', 'jetzt'),
(3, 'Zahlen & Kennenlernen', 'number', 'Zahl, Ziffer'),
(3, 'Zahlen & Kennenlernen', 'one', 'eins, ein, eine'),
(3, 'Zahlen & Kennenlernen', 'two', 'zwei'),
(3, 'Zahlen & Kennenlernen', 'three', 'drei'),
(3, 'Zahlen & Kennenlernen', 'four', 'vier'),
(3, 'Zahlen & Kennenlernen', 'five', 'fünf'),
(3, 'Zahlen & Kennenlernen', 'six', 'sechs'),
(3, 'Zahlen & Kennenlernen', 'seven', 'sieben'),
(3, 'Zahlen & Kennenlernen', 'eight', 'acht'),
(3, 'Zahlen & Kennenlernen', 'nine', 'neun'),
(3, 'Zahlen & Kennenlernen', 'ten', 'zehn'),
(3, 'Zahlen & Kennenlernen', 'eleven', 'elf'),
(3, 'Zahlen & Kennenlernen', 'twelve', 'zwölf');
